environment:
  IMAGE_NAME: ''
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_NAMESPACE: cf
  CAS_NAME: scone-cas
  DESTINATION_IMAGE_NAME: ''
  SCONE_VERSION: 6.1.0-rc.0
  CVM_MODE: --cvm
  SCONE_ENCLAVE: --scone-enclave
  REGISTRY: ''
  REGISTRY_TOKEN: ''
  REGISTRY_USER: ''

