environment:
  IMAGE_NAME: registry.scontain.com/k8s-scone-images/web-server:native
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_NAMESPACE: default
  CAS_NAME: cas
  DESTINATION_IMAGE_NAME: registry.scontain.com/workshop/web-server:protected
  SCONE_RUNTIME_VERSION: 6.1.0-rc.0
  CVM_MODE: --cvm
  SCONE_ENCLAVE: --scone-enclave
  REGISTRY: registry.scontain.com
