import os
import time
import hashlib

# API_USER is set in the manifest and visible to the cluster admin.
user = os.environ.get('API_USER', None)
# API_PASSWORD is generated by CAS and never visible to anyone — not even the cluster admin.
pw = os.environ.get('API_PASSWORD', None)

if user is None or pw is None:
    print("Not all required environment variables are defined.")
    exit(1)

print(f"Version 1: Hello, '{user}' - thanks for passing along the API_PASSWORD", flush=True)

pw_checksum = hashlib.md5(pw.encode('utf-8')).hexdigest()
print(f"The checksum of the original API_PASSWORD is '{pw_checksum}'", flush=True)

while True:
    new_user = os.environ.get('API_USER', None)
    print(f"Hello, user '{new_user}'!", flush=True)
    if new_user != user:
        print(f"Integrity violation: API_USER changed from '{user}' to '{new_user}'!")
        exit(1)

    new_pw = os.environ.get('API_PASSWORD', None)
    new_pw_checksum = hashlib.md5(new_pw.encode('utf-8')).hexdigest() if new_pw else None
    print(f"The checksum of the current password is '{new_pw_checksum}'", flush=True)
    if new_pw_checksum != pw_checksum:
        print(f"Integrity violation: API_PASSWORD checksum changed from '{pw_checksum}' to '{new_pw_checksum}'!")
        exit(1)

    print("Running Version 1. Update by applying the v2 confidential manifest.", flush=True)
    time.sleep(10)
