environment:
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_NAMESPACE: default
  CAS_NAME: cas
  SCONE_VERSION: 7.0.0-alpha.1
  CVM_MODE: 'false'
  SCONE_ENCLAVE: 'false'
  REGISTRY: registry.scontain.com
  REGISTRY_TOKEN: ''
  REGISTRY_USER: ''
  CLIENT_IMAGE: registry.scontain.com/workshop/network-policy:client
  SERVER_IMAGE: registry.scontain.com/workshop/network-policy:server
  SCRIPT_DIR: .
