environment:
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_NAMESPACE: cf
  CAS_NAME: scone-cas
  SCONE_VERSION: 6.1.0-rc.0
  CVM_MODE: 'true'
  SCONE_ENCLAVE: 'true'
  REGISTRY: ''
  REGISTRY_TOKEN: ''
  REGISTRY_USER: ''
  CLIENT_IMAGE: ''
  SERVER_IMAGE: ''
  SCRIPT_DIR: .
