environment:
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_NAMESPACE: default
  CAS_NAME: cas
  SCONE_VERSION: 6.1.0-rc.0
  CVM_MODE: 'true'
  SCONE_ENCLAVE: 'true'
  REGISTRY: registry.scontain.com
  REGISTRY_TOKEN: ''
  REGISTRY_USER: ''
  CLIENT_IMAGE: registry.scontain.com/workshop/network-policy:client
  SERVER_IMAGE: registry.scontain.com/workshop/network-policy:server
  SCRIPT_DIR: .
