environment:
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_NAMESPACE: default
  CAS_NAME: cas
  SCONE_RUNTIME_VERSION: 6.1.0-rc.0
  CVM_MODE: 'true'
  SCONE_ENCLAVE: 'true'
  REGISTRY: registry.scontain.com
  REGISTRY_TOKEN: ''
  REGISTRY_USER: ''
  IMAGE_NAME: registry.scontain.com/k8s-scone-images/flask-redis:latest
  NAMESPACE: scone-tools
  SIGNER: |-
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAvSRST+dhEaX42c6VkY1Sv+KVelnSup96M6TMHOlqcrg=
    -----END PUBLIC KEY-----
