environment:
  IMAGE_NAME: registry.scontain.com/k8s-scone-images/image-signing:native
  IMAGE_PULL_SECRET_NAME: sconeapps
  REPO_CREDENTIALS: /home/amandio/.docker/config.json
  CAS_NAMESPACE: default
  CAS_NAME: cas
  DESTINATION_IMAGE_NAME: registry.scontain.com/k8s-scone-images/image-signing:scone
  CVM_MODE: ''
  SCONE_ENCLAVE: ''
  REGISTRY: registry.scontain.com
  SCONE_RUNTIME_VERSION: 6.1.0-rc.0
  NAMESPACE: ci-scone-td-build
