#!/usr/bin/env bash
# Generated file. Do not edit manually.

set -euo pipefail

VIOLET='\033[38;5;141m'
ORANGE='\033[38;5;208m'
RESET='\033[0m'

show_help() {
  cat <<USAGE
Usage: $0 [--help] [--non-interactive]

Runs shell commands extracted from software-updates/README.md.

Options:
  --help             Show this help message and exit.
  --non-interactive  Do not force confirmation for existing tplenv values.
USAGE
}

NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help)
      show_help
      exit 0
      ;;
    --non-interactive)
      NON_INTERACTIVE=true
      unset CONFIRM_ALL_ENVIRONMENT_VARIABLES || true
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "Error: Unknown option '$1'." >&2
      show_help >&2
      exit 1
      ;;
    *)
      echo "Error: This script does not accept positional arguments." >&2
      show_help >&2
      exit 1
      ;;
  esac
done

if [[ $# -gt 0 ]]; then
  echo "Error: This script does not accept positional arguments." >&2
  show_help >&2
  exit 1
fi

if ! $NON_INTERACTIVE; then
  CONFIRM_ALL_ENVIRONMENT_VARIABLES="--force"
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
expected_workdir="$(cd "${script_dir}/.." && pwd)"
expected_invocation="./$(basename "${script_dir}")/$(basename "$0")"

if [[ "$(pwd)" != "$expected_workdir" ]]; then
  echo "Error: Wrong working directory." >&2
  echo "Expected working directory: $expected_workdir" >&2
  echo "Run this script as: $expected_invocation" >&2
  exit 1
fi

printf "${VIOLET}"
printf '%s\n' '# Software Updates for Confidential Python Applications'
printf '%s\n' ''
printf '%s\n' 'This example demonstrates how to perform a **software update** of a confidential Python application using SCONE and `scone-td-build`. Two versions of the application are built and deployed as a Kubernetes Deployment:'
printf '%s\n' ''
printf '%s\n' '- **Version 1** — the initial deployment, running in a loop that continuously verifies `API_PASSWORD`'
printf '%s\n' '- **Version 2** — the updated version, replacing Version 1 via a Kubernetes rolling update'
printf '%s\n' ''
printf '%s\n' 'The key point of the demo: `API_PASSWORD` is **generated by CAS** on first session creation via a `SconeSecret` — nobody sets it, not even the cluster admin. It lives only inside the enclave. After the software update, Version 2 receives the **same CAS-generated password** (CAS auto-migrates `ascii` secrets when a session is updated under the same namespace), and the application actively verifies this by comparing checksums.'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Project Structure'
printf '%s\n' ''
printf '%s\n' 'software-updates/'
printf '%s\n' '├── print_env1.py                  # Version 1: prints checksum, loops every 10s'
printf '%s\n' '├── print_env2.py                  # Version 2: same loop, different greeting'
printf '%s\n' '├── Dockerfile                     # Builds either version via --build-arg VERSION=1|2'
printf '%s\n' '├── requirements.txt               # No external dependencies (stdlib only)'
printf '%s\n' '├── scone.v1.template.yaml         # SCONE Register + Apply template for Version 1'
printf '%s\n' '├── scone.v2.template.yaml         # SCONE Register + Apply template for Version 2'
printf '%s\n' '├── environment-variables.md       # tplenv variable definitions'
printf '%s\n' '├── registry.credentials.md        # tplenv registry credential definitions'
printf '%s\n' '├── k8s/'
printf '%s\n' '│   ├── manifest.v1.template.yaml  # Kubernetes Deployment template for Version 1'
printf '%s\n' '│   ├── manifest.v2.template.yaml  # Kubernetes Deployment template for Version 2'
printf '%s\n' '│   └── scone-secret.yaml          # SconeSecret: CAS generates API_PASSWORD'
printf '%s\n' '└── README.md'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Prerequisites'
printf '%s\n' ''
printf '%s\n' '- A token for accessing `scone.cloud` images on `registry.scontain.com`'
printf '%s\n' '- A Kubernetes cluster with SGX or CVM support'
printf '%s\n' '- The Kubernetes command-line tool (`kubectl`)'
printf '%s\n' '- Rust `cargo` (`curl --proto '\''=https'\'' --tlsv1.2 -sSf https://sh.rustup.rs | sh`)'
printf '%s\n' '- `tplenv` (`cargo install tplenv`) and `retry-spinner` (`cargo install retry-spinner`)'
printf '%s\n' '- `docker` with push access to a registry your cluster can pull from'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 1. Set Up the Environment'
printf '%s\n' ''
printf '%s\n' 'Assume you start in `scone-td-build-demos` and switch into this demo directory:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Enter `software-updates` and remember the previous directory.'
printf '%s\n' 'pushd software-updates'
printf '%s\n' '# Remove generated state files from any previous run.'
printf '%s\n' 'rm -f software-updates-demo.json scone.v1.yaml scone.v2.yaml manifest.prod.sanitized.yaml manifest.prod.session.yaml || true'
printf "${RESET}"

# Enter `software-updates` and remember the previous directory.
pushd software-updates
# Remove generated state files from any previous run.
rm -f software-updates-demo.json scone.v1.yaml scone.v2.yaml manifest.prod.sanitized.yaml manifest.prod.session.yaml || true

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' 'Set `SIGNER` for policy signing and generate a unique CAS session namespace for this run:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Export the required environment variable for the next steps.'
printf '%s\n' 'export SIGNER="$(scone self show-session-signing-key)"'
printf '%s\n' '# Generate a unique session namespace shared by both v1 and v2 builds.'
printf '%s\n' 'export SESSION_NAMESPACE="software-update-$(openssl rand -hex 4)"'
printf '%s\n' '# Print a status message.'
printf '%s\n' 'echo "SESSION_NAMESPACE=${SESSION_NAMESPACE}"'
printf "${RESET}"

# Export the required environment variable for the next steps.
export SIGNER="$(scone self show-session-signing-key)"
# Generate a unique session namespace shared by both v1 and v2 builds.
export SESSION_NAMESPACE="software-update-$(openssl rand -hex 4)"
# Print a status message.
echo "SESSION_NAMESPACE=${SESSION_NAMESPACE}"

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' 'Load the full variable set from `environment-variables.md`:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Load environment variables from the tplenv definition file.'
printf '%s\n' 'eval $(tplenv --file environment-variables.md --create-values-file --context --eval ${CONFIRM_ALL_ENVIRONMENT_VARIABLES-} --output /dev/null)'
printf "${RESET}"

# Load environment variables from the tplenv definition file.
eval $(tplenv --file environment-variables.md --create-values-file --context --eval ${CONFIRM_ALL_ENVIRONMENT_VARIABLES-} --output /dev/null)

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 2. Build and Push the Native Docker Images'
printf '%s\n' ''
printf '%s\n' 'The Dockerfile accepts a `VERSION` build argument to choose which Python script to embed. Build both versions:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Build the Version 1 container image.'
printf '%s\n' 'docker build --build-arg VERSION=1 -t ${IMAGE_NAME_V1} .'
printf '%s\n' '# Push the Version 1 container image to the registry.'
printf '%s\n' 'docker push ${IMAGE_NAME_V1}'
printf '%s\n' '# Build the Version 2 container image.'
printf '%s\n' 'docker build --build-arg VERSION=2 -t ${IMAGE_NAME_V2} .'
printf '%s\n' '# Push the Version 2 container image to the registry.'
printf '%s\n' 'docker push ${IMAGE_NAME_V2}'
printf "${RESET}"

# Build the Version 1 container image.
docker build --build-arg VERSION=1 -t ${IMAGE_NAME_V1} .
# Push the Version 1 container image to the registry.
docker push ${IMAGE_NAME_V1}
# Build the Version 2 container image.
docker build --build-arg VERSION=2 -t ${IMAGE_NAME_V2} .
# Push the Version 2 container image to the registry.
docker push ${IMAGE_NAME_V2}

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 3. Create the Kubernetes Namespace'
printf '%s\n' ''
printf '%s\n' 'We try to ensure the namespace exists. This may fail when running in a container already in the target namespace, so we ignore that failure.'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Create the Kubernetes namespace if it does not already exist.'
printf '%s\n' 'kubectl create namespace ${NAMESPACE} --dry-run=client -o yaml | kubectl apply -f - 2> /dev/null || echo "Patching namespace ${NAMESPACE} failed -- ignoring this"'
printf "${RESET}"

# Create the Kubernetes namespace if it does not already exist.
kubectl create namespace ${NAMESPACE} --dry-run=client -o yaml | kubectl apply -f - 2> /dev/null || echo "Patching namespace ${NAMESPACE} failed -- ignoring this"

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 4. Add a Docker Registry Secret'
printf '%s\n' ''
printf '%s\n' 'A pull secret is needed to pull the confidential container images.'
printf '%s\n' ''
printf '%s\n' '- `$REGISTRY` — the registry hostname (default: `registry.scontain.com`)'
printf '%s\n' '- `$REGISTRY_USER` — your registry login name'
printf '%s\n' '- `$REGISTRY_TOKEN` — your registry pull token (see [how to create a token](https://sconedocs.github.io/registry/))'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Check whether the pull secret already exists.'
printf '%s\n' 'if kubectl get secret -n "${NAMESPACE}" "${IMAGE_PULL_SECRET_NAME}" >/dev/null 2>&1; then'
printf '%s\n' '  # Print a status message.'
printf '%s\n' '  echo "Secret ${IMAGE_PULL_SECRET_NAME} already exists"'
printf '%s\n' 'else'
printf '%s\n' '  # Print a status message.'
printf '%s\n' '  echo "Secret ${IMAGE_PULL_SECRET_NAME} does not exist - creating now."'
printf '%s\n' '  # Create the Docker registry pull secret.'
printf '%s\n' '  kubectl create secret docker-registry -n "${NAMESPACE}" "${IMAGE_PULL_SECRET_NAME}" --docker-server=$REGISTRY --docker-username=$REGISTRY_USER --docker-password=$REGISTRY_TOKEN'
printf '%s\n' 'fi'
printf "${RESET}"

# Check whether the pull secret already exists.
if kubectl get secret -n "${NAMESPACE}" "${IMAGE_PULL_SECRET_NAME}" >/dev/null 2>&1; then
  # Print a status message.
  echo "Secret ${IMAGE_PULL_SECRET_NAME} already exists"
else
  # Print a status message.
  echo "Secret ${IMAGE_PULL_SECRET_NAME} does not exist - creating now."
  # Create the Docker registry pull secret.
  kubectl create secret docker-registry -n "${NAMESPACE}" "${IMAGE_PULL_SECRET_NAME}" --docker-server=$REGISTRY --docker-username=$REGISTRY_USER --docker-password=$REGISTRY_TOKEN
fi

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 5. Render the Manifests'
printf '%s\n' ''
printf '%s\n' 'Render the Kubernetes deployment manifests and SCONE configurations for both versions:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Render the Version 1 SCONE configuration.'
printf '%s\n' 'tplenv --file scone.v1.template.yaml --create-values-file --output scone.v1.yaml --indent'
printf '%s\n' '# Render the Version 2 SCONE configuration.'
printf '%s\n' 'tplenv --file scone.v2.template.yaml --create-values-file --output scone.v2.yaml --indent'
printf "${RESET}"

# Render the Version 1 SCONE configuration.
tplenv --file scone.v1.template.yaml --create-values-file --output scone.v1.yaml --indent
# Render the Version 2 SCONE configuration.
tplenv --file scone.v2.template.yaml --create-values-file --output scone.v2.yaml --indent

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Part 1 — Deploy Version 1 (SCONE)'
printf '%s\n' ''
printf '%s\n' 'In the SCONE deployment, `API_PASSWORD` is **generated by CAS** via `k8s/scone-secret.yaml`. Nobody sets it — CAS creates it when the session is first applied and injects it into the enclave at runtime. It never appears in any Kubernetes manifest or Secret visible to a cluster administrator.'
printf '%s\n' ''
printf '%s\n' '### Step 6. Generate the signing key'
printf '%s\n' ''
printf '%s\n' 'When protecting binaries for confidential execution, `scone-td-build` signs them with a key stored in `identity.pem`:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Check whether the signing key needs to be generated.'
printf '%s\n' 'if [ ! -f identity.pem ]; then'
printf '%s\n' '  # Print a status message.'
printf '%s\n' '  echo "Generating identity.pem ..."'
printf '%s\n' '  # Generate the signing key for confidential binaries.'
printf '%s\n' '  openssl genrsa -3 -out identity.pem 3072'
printf '%s\n' 'else'
printf '%s\n' '  # Print a status message.'
printf '%s\n' '  echo "identity.pem already exists."'
printf '%s\n' 'fi'
printf "${RESET}"

# Check whether the signing key needs to be generated.
if [ ! -f identity.pem ]; then
  # Print a status message.
  echo "Generating identity.pem ..."
  # Generate the signing key for confidential binaries.
  openssl genrsa -3 -out identity.pem 3072
else
  # Print a status message.
  echo "identity.pem already exists."
fi

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '### Step 7. Build the confidential image and session for Version 1'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Remove any existing state file.'
printf '%s\n' 'rm -f software-updates-demo.json || true'
printf '%s\n' '# Generate the confidential image and sanitized manifest from the SCONE configuration.'
printf '%s\n' 'scone-td-build from -y scone.v1.yaml'
printf "${RESET}"

# Remove any existing state file.
rm -f software-updates-demo.json || true
# Generate the confidential image and sanitized manifest from the SCONE configuration.
scone-td-build from -y scone.v1.yaml

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' 'This command:'
printf '%s\n' ''
printf '%s\n' '- Registers and pushes the Version 1 confidential image (`${DESTINATION_IMAGE_NAME_V1}`)'
printf '%s\n' '- Creates a CAS session under namespace `${SESSION_NAMESPACE}` with a `SconeSecret` that tells CAS to generate `API_PASSWORD`'
printf '%s\n' '- Produces `manifest.prod.sanitized.yaml` referencing the confidential image — `API_PASSWORD` does not appear in it'
printf '%s\n' ''
printf '%s\n' '### Step 8. Deploy Version 1 (SCONE)'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Apply the Kubernetes manifest.'
printf '%s\n' 'kubectl apply -f manifest.prod.sanitized.yaml --namespace ${NAMESPACE}'
printf '%s\n' '# Wait for the deployment rollout to complete.'
printf '%s\n' 'kubectl rollout status deployment/python-hello-user -n ${NAMESPACE} --timeout=300s'
printf "${RESET}"

# Apply the Kubernetes manifest.
kubectl apply -f manifest.prod.sanitized.yaml --namespace ${NAMESPACE}
# Wait for the deployment rollout to complete.
kubectl rollout status deployment/python-hello-user -n ${NAMESPACE} --timeout=300s

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '### Step 9. Verify the Version 1 deployment'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Show the most recent logs and note the API_PASSWORD checksum.'
printf '%s\n' 'retry-spinner --retries 10 --wait 5 -- kubectl logs -n ${NAMESPACE} deployment/python-hello-user --tail=10'
printf "${RESET}"

# Show the most recent logs and note the API_PASSWORD checksum.
retry-spinner --retries 10 --wait 5 -- kubectl logs -n ${NAMESPACE} deployment/python-hello-user --tail=10

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' 'You should see output repeating every 10 seconds:'
printf '%s\n' ''
printf '%s\n' 'Version 1: Hello, '\''myself'\'' - thanks for passing along the API_PASSWORD'
printf '%s\n' 'The checksum of the original API_PASSWORD is '\''<checksum>'\'''
printf '%s\n' 'Hello, user '\''myself'\''!'
printf '%s\n' 'The checksum of the current password is '\''<checksum>'\'''
printf '%s\n' 'Running Version 1. Update by applying the v2 confidential manifest.'
printf '%s\n' ''
printf '%s\n' 'Note the checksum — it must match after the software update.'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Part 2 — Software Update to Version 2'
printf '%s\n' ''
printf '%s\n' '`API_PASSWORD` is **not modified** during this update. Both v1 and v2 Apply CRDs share the same `SESSION_NAMESPACE`, so `scone-td-build` updates the existing CAS session rather than creating a new one. CAS auto-migrates `ascii` secrets on session update, preserving the same generated value.'
printf '%s\n' ''
printf '%s\n' '### Step 10. Build the confidential image and update the session for Version 2'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Generate the confidential image and sanitized manifest from the SCONE configuration.'
printf '%s\n' 'scone-td-build from -y scone.v2.yaml'
printf "${RESET}"

# Generate the confidential image and sanitized manifest from the SCONE configuration.
scone-td-build from -y scone.v2.yaml

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' 'This command:'
printf '%s\n' ''
printf '%s\n' '- Registers and pushes the Version 2 confidential image (`${DESTINATION_IMAGE_NAME_V2}`)'
printf '%s\n' '- Updates the existing CAS session (same `SESSION_NAMESPACE` as Version 1) — CAS preserves `API_PASSWORD`'
printf '%s\n' '- Produces `manifest.prod.sanitized.yaml` referencing the Version 2 confidential image'
printf '%s\n' ''
printf '%s\n' '### Step 11. Apply the rolling update'
printf '%s\n' ''
printf '%s\n' 'Applying the new manifest triggers a Kubernetes rolling update — Version 1 pods are replaced by Version 2 pods without downtime:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Apply the updated Kubernetes manifest.'
printf '%s\n' 'kubectl apply -f manifest.prod.sanitized.yaml --namespace ${NAMESPACE}'
printf '%s\n' '# Wait for the rolling update to complete.'
printf '%s\n' 'kubectl rollout status deployment/python-hello-user -n ${NAMESPACE} --timeout=300s'
printf "${RESET}"

# Apply the updated Kubernetes manifest.
kubectl apply -f manifest.prod.sanitized.yaml --namespace ${NAMESPACE}
# Wait for the rolling update to complete.
kubectl rollout status deployment/python-hello-user -n ${NAMESPACE} --timeout=300s

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' '### Step 12. Verify the Version 2 deployment'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Show the most recent logs from Version 2.'
printf '%s\n' 'retry-spinner --retries 10 --wait 5 -- kubectl logs -n ${NAMESPACE} deployment/python-hello-user --tail=10'
printf "${RESET}"

# Show the most recent logs from Version 2.
retry-spinner --retries 10 --wait 5 -- kubectl logs -n ${NAMESPACE} deployment/python-hello-user --tail=10

printf "${VIOLET}"
printf '%s\n' ''
printf '%s\n' 'You should see output such as:'
printf '%s\n' ''
printf '%s\n' 'Version 2 (updated): Hello, '\''myself'\'' - software update successful!'
printf '%s\n' 'The checksum of the original API_PASSWORD is '\''<checksum>'\'''
printf '%s\n' 'Hello, user '\''myself'\''!'
printf '%s\n' 'The checksum of the current password is '\''<checksum>'\'''
printf '%s\n' 'Running Version 2.'
printf '%s\n' ''
printf '%s\n' 'The **checksum must match** the one printed by Version 1, confirming that `API_PASSWORD` was generated by CAS once and preserved across the software update.'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Cleanup'
printf '%s\n' ''
printf '%s\n' 'Remove all deployed resources when you are finished:'
printf '%s\n' ''
printf "${RESET}"

printf "${ORANGE}"
printf '%s\n' '# Delete the Kubernetes deployment.'
printf '%s\n' 'kubectl delete deployment python-hello-user --namespace ${NAMESPACE} --ignore-not-found'
printf '%s\n' '# Return to the previous working directory.'
printf '%s\n' 'popd'
printf "${RESET}"

# Delete the Kubernetes deployment.
kubectl delete deployment python-hello-user --namespace ${NAMESPACE} --ignore-not-found
# Return to the previous working directory.
popd

