apiVersion: scone.cloud/v1
kind: Register
metadata:
  name: configmap-example
spec:
  protected_image: ${DEMO_IMAGE}
  unprotected_image: ${DEMO_IMAGE}
  destination_image: ${DESTINATION_IMAGE_NAME}
  enforce: ["/usr/local/bin/folder-reader"]
  push_scone_image: true
  version: ${SCONE_VERSION}
  cvm: ${CVM_MODE}
  manifest_env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
---
apiVersion: scone.cloud/v1
kind: Apply
metadata:
  name: configmap-example
spec:
  file:
    - "manifests/manifest.yaml"
  output_manifest_file: "manifests/manifest.prod.sanitized.yaml"
  output_session_file: "manifests/manifest.prod.session.yaml"
  cas_address:
    address: ${CAS_NAME}.${CAS_NAMESPACE}
  session_env:
    - {name: SCONE_VERSION, value: "1"}
  manifest_env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
  permissive: true
  spol: true
  cvm: ${CVM_MODE}
  scone_enclave: ${SCONE_ENCLAVE}
  access_policy:
    read:
      - ANY
    update:
      - signer: |
          ${SIGNER}
    create_sessions:
      - signer: |
          ${SIGNER}