environment:
  DEMO_IMAGE: ''
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_NAMESPACE: cf
  CAS_NAME: scone-cas
  DESTINATION_IMAGE_NAME: ''
  SCONE_VERSION: 6.1.0-rc.0
  CVM_MODE: 'true'
  SCONE_ENCLAVE: 'true'
  REGISTRY: ''
  REGISTRY_TOKEN: ''
  REGISTRY_USER: ''
  SIGNER: |-
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAntUKD760EYRvgMd7seRLx2asH8u2ZZuULJBG6MEARl0=
    -----END PUBLIC KEY-----
